[[security]]
= REST Basics - Security

Any non public API's must be secured; that is API's exposed via https://api.landonline.govt.nz/.
This will be imply  <<219, x-audience>> has been set to company-internal or bff-internal and <<105, scopes are set correctly>>.

[#104]
== {MUST} secure API

Non public APIs are protected using JWT Access tokens provided by the platform IAM token service (Currently Keycloak) and must be armed with authentication and authorization.

As part of the API definition you must specify that the API is protected using  `http` typed `bearer` security schemes defined in the
https://swagger.io/docs/specification/authentication/bearer-authentication/[Open API Bearer Authentication] it is based on OAuth2.0 {RFC-6750}[RFC 6750] defining the standard header
`Auhorization: Bearer <token>`.
The following code snippet shows how to define the bearer security scheme.

[source,yaml]
----
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
----

[#105]
== {MUST} define and assign permissions (scopes)
At LINZ (STEP) every API must define and set security permissions, also known as "scopes" A decision was made that we would use resource based scopes, so this implies each resource MUST define at least one scope. A scope is a way to limit the type of access that a client has to a particular resource or service by the user who’s using the app. Scopes MAY be reused between API's if there is a logical service/boundary level (e.g., search, fees) but at least one scope must be defined per resource. (If in doubt check with Security)

As of the time of writing, only a single default scope is definable per API ( Resource ) -- (Kapua is in the progress of defing endpoint level scopes at what this means)


The format for scopes follows the regex pattern `[a-zA-Z\-]{4,15}:default`. This means the name of the scope should consist of 4 to 15 alphanumeric characters (or hyphens), followed by `:default`. The `:default` part indicates that these are the default permissions for the respective service.

Scopes are defined as part of the security requirement object at the root level of your API definition, allowing for a default scope that applies to all operations within the API. Please note that currently, only the root security can be set in our system.

Example:

[source,yaml]
----
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- BearerAuth: [ 'search:default' ]
paths:
  /registeredclients-only-information:
    get:
      summary: Provides information about ...
               Accessible by any user; permissions needed.
----

In the above example, the default scope `search:default` is applied at the root level of the API, allowing access to search operations for any client who has this scope on behalf of the user.

It's critical to understand that any new scope must be https://github.com/linz/landonline-auth/blob/master/docs/how-to-add-new-client-scope.md#adding-a-new-scope[created/configured in the Identity Provider (IDP)] before it can be used by a resource server. Also, the relevant clients must be registered to get that scope. This process is documented in https://github.com/linz/landonline-auth/blob/master/docs/how-to-add-new-client-scope.md[Granting client scope to a client].

Remember that the resource owner squad holds the authority to approve a client registering to a scope. Therefore, always ensure their approval before proceeding with scope creation.

For audiences like the external-public, there's no requirement to define a specific scope. If a single service needs to serve multiple audiences, it's often best to create separate API specifications to manage access control effectively. Refer to <<219, MUST provide audience>> for more details.








